# Generated by Django 5.2.6 on 2025-09-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(choices=[('idle', 'Ocioso'), ('collecting_info', 'Coletando Informações'), ('selecting_doctor', 'Selecionando Médico'), ('choosing_schedule', 'Escolhendo Horário'), ('confirming', 'Confirmando'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='idle', max_length=50)),
                ('specialty_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('selected_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sessão de Conversa',
                'verbose_name_plural': 'Sessões de Conversa',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='RAGCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cache RAG',
                'verbose_name_plural': 'Caches RAG',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuário'), ('bot', 'Bot'), ('system', 'Sistema')], max_length=10)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_gateway.conversationsession')),
            ],
            options={
                'verbose_name': 'Mensagem da Conversa',
                'verbose_name_plural': 'Mensagens da Conversa',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('insurance', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='pending', max_length=20)),
                ('handoff_link', models.URLField(blank=True, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_request', to='api_gateway.conversationsession')),
            ],
            options={
                'verbose_name': 'Solicitação de Agendamento',
                'verbose_name_plural': 'Solicitações de Agendamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
