# Generated by Django 5.2.6 on 2025-09-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('idle', 'Ocioso'), ('collecting_patient_info', 'Coletando Dados do Paciente'), ('collecting_info', 'Coletando Informações'), ('selecting_doctor', 'Selecionando Médico'), ('choosing_schedule', 'Escolhendo Horário'), ('confirming', 'Confirmando'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='idle', max_length=50),
        ),
    ]
