# Generated by Django 5.2.6 on 2025-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0002_alter_conversationsession_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='name_confirmed',
            field=models.BooleanField(default=False, help_text='Nome do paciente foi confirmado'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='pending_name',
            field=models.CharField(blank=True, help_text='Nome extraído aguardando confirmação', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('idle', 'Ocioso'), ('collecting_patient_info', 'Coletando Dados do Paciente'), ('collecting_info', 'Coletando Informações'), ('confirming_name', 'Confirmando Nome do Paciente'), ('selecting_doctor', 'Selecionando Médico'), ('choosing_schedule', 'Escolhendo Horário'), ('confirming', 'Confirmando'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='idle', max_length=50),
        ),
    ]
