# Generated by Django 5.2.6 on 2025-10-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0003_conversationsession_name_confirmed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAGCache',
        ),
    ]
