# Generated by Django 5.2.6 on 2025-10-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0004_delete_ragcache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
    ]
