# Generated by Django 5.2.6 on 2025-10-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0006_alter_conversationsession_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='selected_specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('idle', 'Ocioso'), ('collecting_patient_info', 'Coletando Dados do Paciente'), ('collecting_info', 'Coletando Informações'), ('confirming_name', 'Confirmando Nome do Paciente'), ('selecting_doctor', 'Selecionando Médico'), ('selecting_specialty', 'Selecionando Especialidade'), ('choosing_schedule', 'Escolhendo Horário'), ('confirming', 'Confirmando')], default='idle', max_length=50),
        ),
    ]
