# Generated by Django 5.2.6 on 2025-10-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0007_conversationsession_selected_specialty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationsession',
            name='specialty_interest',
        ),
    ]
