# Generated by Django 5.2.6 on 2025-10-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0008_remove_conversationsession_specialty_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='previous_state',
            field=models.CharField(blank=True, help_text='Estado anterior antes de pausar para dúvidas', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('idle', 'Ocioso'), ('collecting_patient_info', 'Coletando Dados do Paciente'), ('collecting_info', 'Coletando Informações'), ('answering_questions', 'Respondendo Dúvidas'), ('confirming_name', 'Confirmando Nome do Paciente'), ('selecting_doctor', 'Selecionando Médico'), ('selecting_specialty', 'Selecionando Especialidade'), ('choosing_schedule', 'Escolhendo Horário'), ('confirming', 'Confirmando')], default='idle', max_length=50),
        ),
    ]
