# Generated by Django 5.2.6 on 2025-10-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0009_add_question_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('idle', 'Ocioso'), ('collecting_patient_info', 'Coletando Dados do Paciente'), ('collecting_info', 'Coletando Informações'), ('answering_questions', 'Respondendo Dúvidas'), ('confirming_name', 'Confirmando Nome do Paciente'), ('selecting_doctor', 'Selecionando Médico'), ('selecting_specialty', 'Selecionando Especialidade'), ('choosing_schedule', 'Escolhendo Horário'), ('confirming', 'Confirmando'), ('confirmed', 'Agendamento Confirmado')], default='idle', max_length=50),
        ),
    ]
