# Generated by Django 5.2.6 on 2025-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0010_add_confirmed_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('idle', 'Ocioso'), ('collecting_patient_info', 'Coletando Dados do Paciente'), ('answering_questions', 'Respondendo Dúvidas'), ('confirming_name', 'Confirmando Nome do Paciente'), ('selecting_doctor', 'Selecionando Médico'), ('selecting_specialty', 'Selecionando Especialidade'), ('choosing_schedule', 'Escolhendo Horário'), ('confirming', 'Confirmando')], default='idle', max_length=50),
        ),
    ]
