# Generated by Django 5.2.6 on 2025-09-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_usuario', models.CharField(max_length=20)),
                ('nome_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web', 'Web'), ('telegram', 'Telegram')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('pausada', 'Pausada')], default='ativa', max_length=20)),
                ('contexto_atual', models.JSONField(default=dict, help_text='Contexto da conversa em JSON')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('telefone_paciente', models.CharField(max_length=20)),
                ('tipo_consulta', models.CharField(max_length=50)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('medico_preferido', models.CharField(blank=True, max_length=100)),
                ('convenio', models.CharField(blank=True, max_length=100)),
                ('data_preferida', models.DateField(blank=True, null=True)),
                ('horario_preferido', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_agent.conversa')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuário'), ('bot', 'Bot'), ('sistema', 'Sistema')], max_length=10)),
                ('conteudo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados da mensagem')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='flow_agent.conversa')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
