# Generated by Django 5.2.6 on 2025-09-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow_agent', '0002_remove_mensagem_conversa_delete_agendamento_and_more'),
        ('rag_agent', '0002_clinicainfo_whatsapp_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(help_text='ID único do usuário no WhatsApp (número de telefone)', max_length=50, unique=True)),
                ('nome_usuario', models.CharField(blank=True, help_text='Nome do usuário (coletado durante a conversa)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='ativa', max_length=20)),
                ('contexto_atual', models.JSONField(blank=True, default=dict, help_text='Dados contextuais da conversa (intenção atual, dados coletados, etc.)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atividade', models.DateTimeField(auto_now=True)),
                ('medico_selecionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='rag_agent.medico')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-data_ultima_atividade'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Mensagem do Usuário'), ('saida', 'Resposta do Bot'), ('sistema', 'Mensagem do Sistema')], max_length=10)),
                ('conteudo', models.TextField(help_text='Conteúdo da mensagem')),
                ('intencao_detectada', models.CharField(blank=True, help_text="Intenção detectada pela IA (ex: 'agendar_consulta', 'buscar_info')", max_length=50, null=True)),
                ('confianca_intencao', models.FloatField(blank=True, help_text='Nível de confiança da detecção de intenção (0.0 a 1.0)', null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='flow_agent.conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('motivo_consulta', models.TextField(blank=True, help_text='Descrição do motivo da consulta', null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('google_calendar_event_id', models.CharField(blank=True, help_text='ID do evento no Google Calendar', max_length=255, null=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rag_agent.convenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='rag_agent.medico')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='flow_agent.conversa')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_consulta', 'hora_consulta'],
                'unique_together': {('medico', 'data_consulta', 'hora_consulta')},
            },
        ),
    ]
