# Generated by Django 5.2.6 on 2025-09-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_agent', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='medico_selecionado',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='conversa',
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='Conversa',
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
