# Generated by Django 5.2.6 on 2025-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicainfo',
            name='whatsapp_contato',
            field=models.CharField(default=73988221003, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicainfo',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
