# Generated by Django 5.2.6 on 2025-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_agent', '0002_clinicainfo_whatsapp_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
