# Generated by Django 5.2.6 on 2025-11-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_agent', '0003_medico_crm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicainfo',
            name='google_calendar_id',
        ),
    ]
